Repository cchaksa/cchaksa-backend, pull requests merged in 2025-03, with the labels that each got.

#1 feat: autofix Setting
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/기능-추가.md
  .github/workflows/autofix.yml
Labels: ✨ Feature

#3 feat/elk-setup
  .gitignore
  build.gradle
  elk-config/docker-compose.yml
  elk-config/elasticsearch/Dockerfile
  elk-config/kibana/Dockerfile
  elk-config/logstash/Dockerfile
  src/main/java/com/chukchuk/haksa/domain/TestApi.java
  src/main/resources/logback.xml
Labels: ⚙ Setting, ✨ Feature

#5 feat/security-setup
  build.gradle
  elk-config/docker-compose.yml
  src/main/java/com/chukchuk/haksa/domain/TestApi.java
  src/main/java/com/chukchuk/haksa/global/security/CustomUserDetails.java
  src/main/java/com/chukchuk/haksa/global/security/SecurityConfig.java
  src/main/java/com/chukchuk/haksa/global/security/SupabaseUser.java
  src/main/java/com/chukchuk/haksa/global/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/chukchuk/haksa/global/security/service/CustomUserDetailsService.java
  src/main/java/com/chukchuk/haksa/global/security/service/SupabaseAuthService.java
  src/main/resources/logback.xml
Labels: 🐞 BugFix, ✨ Feature

#7 feat: Spring Security refactoring
  build.gradle
  src/main/java/com/chukchuk/haksa/ChukchukHaksaApplication.java
  src/main/java/com/chukchuk/haksa/domain/user/model/User.java
  src/main/java/com/chukchuk/haksa/domain/user/repository/UserRepository.java
  src/main/java/com/chukchuk/haksa/global/security/CustomUserDetails.java
  src/main/java/com/chukchuk/haksa/global/security/SecurityConfig.java
  src/main/java/com/chukchuk/haksa/global/security/SupabaseUser.java
  src/main/java/com/chukchuk/haksa/global/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/chukchuk/haksa/global/security/service/CustomUserDetailsService.java
  src/main/java/com/chukchuk/haksa/global/security/service/JwtUtil.java
  src/main/java/com/chukchuk/haksa/global/security/service/SupabaseAuthService.java
Labels: 🔨 Refactor

#10 fix: logstash 포트 연결 안되던 문제 해결
  elk-config/docker-compose.yml
  src/main/resources/logback.xml
Labels: 🐞 BugFix

#12 feat/학기별 성적 및 수강 과목 정보 조회 API 구현
  src/main/java/com/chukchuk/haksa/domain/academic/record/controller/AcademicRecordController.java
  src/main/java/com/chukchuk/haksa/domain/academic/record/dto/AcademicRecordResponse.java
  src/main/java/com/chukchuk/haksa/domain/academic/record/dto/SemesterAcademicRecordDto.java
  src/main/java/com/chukchuk/haksa/domain/academic/record/dto/StudentCourseDto.java
  src/main/java/com/chukchuk/haksa/domain/academic/record/model/SemesterAcademicRecord.java
  src/main/java/com/chukchuk/haksa/domain/academic/record/model/StudentAcademicRecord.java
  src/main/java/com/chukchuk/haksa/domain/academic/record/model/StudentCourse.java
  src/main/java/com/chukchuk/haksa/domain/academic/record/repository/SemesterAcademicRecordRepository.java
  src/main/java/com/chukchuk/haksa/domain/academic/record/repository/StudentCourseRepository.java
  src/main/java/com/chukchuk/haksa/domain/academic/record/service/AcademicRecordService.java
  src/main/java/com/chukchuk/haksa/domain/academic/record/service/SemesterAcademicRecordService.java
  src/main/java/com/chukchuk/haksa/domain/academic/record/service/StudentCourseService.java
  src/main/java/com/chukchuk/haksa/domain/course/model/CourseOffering.java
  src/main/java/com/chukchuk/haksa/domain/user/service/UserService.java
  src/main/java/com/chukchuk/haksa/global/exception/DataNotFoundException.java
  src/main/java/com/chukchuk/haksa/global/security/CustomUserDetails.java
Labels: ✨ Feature

#21 fix: User 테이블에 재연동 시각 컬럼 추가
  src/main/java/com/chukchuk/haksa/domain/user/model/User.java
Labels: 🐞 BugFix

#22 feat: 대시보드 정보 조회 API 개발
  src/main/java/com/chukchuk/haksa/application/dashboard/DashboardController.java
  src/main/java/com/chukchuk/haksa/application/dashboard/DashboardService.java
  src/main/java/com/chukchuk/haksa/application/dashboard/dto/DashboardResponse.java
  src/main/java/com/chukchuk/haksa/domain/academic/record/dto/StudentAcademicRecordDto.java
  src/main/java/com/chukchuk/haksa/domain/academic/record/repository/StudentAcademicRecordRepository.java
  src/main/java/com/chukchuk/haksa/domain/academic/record/service/AcademicRecordService.java
  src/main/java/com/chukchuk/haksa/domain/academic/record/service/SemesterAcademicRecordService.java
  src/main/java/com/chukchuk/haksa/domain/academic/record/service/StudentAcademicRecordService.java
  src/main/java/com/chukchuk/haksa/domain/academic/record/service/StudentCourseService.java
  src/main/java/com/chukchuk/haksa/domain/student/dto/StudentDto.java
  src/main/java/com/chukchuk/haksa/domain/student/repository/StudentRepository.java
  src/main/java/com/chukchuk/haksa/domain/student/service/StudentService.java
  src/main/java/com/chukchuk/haksa/domain/user/service/UserService.java
Labels: ✨ Feature

#24 feat/new-semester
  src/main/java/com/chukchuk/haksa/domain/academic/record/controller/AcademicRecordController.java
  src/main/java/com/chukchuk/haksa/domain/academic/record/repository/SemesterAcademicRecordRepository.java
  src/main/java/com/chukchuk/haksa/domain/academic/record/service/SemesterAcademicRecordService.java
  src/main/java/com/chukchuk/haksa/domain/student/dto/StudentSemesterDto.java
  src/main/java/com/chukchuk/haksa/global/exception/FreshManException.java
Labels: ✨ Feature

#26 feat: Kakao oidc 기반 회원가입/로그인
  src/main/java/com/chukchuk/haksa/domain/user/model/User.java
  src/main/java/com/chukchuk/haksa/global/security/CustomUserDetails.java
  src/main/java/com/chukchuk/haksa/global/security/SecurityConfig.java
  src/main/java/com/chukchuk/haksa/global/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/chukchuk/haksa/global/security/service/JwtUtil.java
  src/main/java/com/chukchuk/haksa/global/security/service/KakaoOidcPublicKeyService.java
  src/main/java/com/chukchuk/haksa/global/security/service/KakaoOidcService.java
Labels: 🔨 Refactor, ✨ Feature

#29 fix: 과목 구분 '복선' 추가
  src/main/java/com/chukchuk/haksa/domain/course/model/CourseOffering.java
  src/main/java/com/chukchuk/haksa/domain/course/model/FacultyDivision.java
Labels: 🐞 BugFix

#30 feat: 졸업 요건 및 학사 성적 정보 조회 API 개발
  src/main/java/com/chukchuk/haksa/domain/academic/record/dto/SemesterAcademicRecordDto.java
  src/main/java/com/chukchuk/haksa/domain/academic/record/repository/SemesterAcademicRecordRepository.java
  src/main/java/com/chukchuk/haksa/domain/academic/record/service/SemesterAcademicRecordService.java
  src/main/java/com/chukchuk/haksa/domain/graduation/controller/GraduationController.java
  src/main/java/com/chukchuk/haksa/domain/graduation/dto/AreaProgressDto.java
  src/main/java/com/chukchuk/haksa/domain/graduation/dto/CourseDto.java
  src/main/java/com/chukchuk/haksa/domain/graduation/dto/GraduationProgressDto.java
  src/main/java/com/chukchuk/haksa/domain/graduation/repository/GraduationQueryRepository.java
  src/main/java/com/chukchuk/haksa/domain/graduation/service/GraduationService.java
Labels: 🐞 BugFix, ✨ Feature

#31 hotfix: 전공 분류 로직 수정
  src/main/java/com/chukchuk/haksa/domain/academic/record/service/AcademicRecordService.java
Labels: 🐞 BugFix

#32 refactor/AcademicRecord Refactoring
  src/main/java/com/chukchuk/haksa/domain/academic/record/controller/AcademicRecordController.java
  src/main/java/com/chukchuk/haksa/domain/academic/record/dto/AcademicRecordResponse.java
  src/main/java/com/chukchuk/haksa/domain/academic/record/repository/SemesterAcademicRecordRepository.java
  src/main/java/com/chukchuk/haksa/domain/academic/record/service/AcademicRecordService.java
  src/main/java/com/chukchuk/haksa/domain/academic/record/service/SemesterAcademicRecordService.java
  src/main/java/com/chukchuk/haksa/domain/graduation/service/GraduationService.java
Labels: 🔨 Refactor

#33 feat: targetGpa 기능 개발
  src/main/java/com/chukchuk/haksa/domain/student/controller/StudentController.java
  src/main/java/com/chukchuk/haksa/domain/student/model/Student.java
  src/main/java/com/chukchuk/haksa/domain/student/service/StudentService.java
Labels: ✨ Feature

#35 fix: api 경로 '/' 누락 수정
  src/main/java/com/chukchuk/haksa/domain/student/controller/StudentController.java
Labels: 🐞 BugFix

#38 feat: 회원 탈퇴 API 구현 #19
  src/main/java/com/chukchuk/haksa/domain/user/controller/UserController.java
  src/main/java/com/chukchuk/haksa/domain/user/service/UserService.java
Labels: 📬 API

#39 refactor: Entity 연관관계 리팩토링
  src/main/java/com/chukchuk/haksa/domain/academic/record/model/SemesterAcademicRecord.java
  src/main/java/com/chukchuk/haksa/domain/academic/record/model/StudentAcademicRecord.java
  src/main/java/com/chukchuk/haksa/domain/academic/record/model/StudentCourse.java
  src/main/java/com/chukchuk/haksa/domain/course/model/CourseOffering.java
  src/main/java/com/chukchuk/haksa/domain/graduation/model/StudentGraduationProgress.java
  src/main/java/com/chukchuk/haksa/domain/student/model/Student.java
  src/main/java/com/chukchuk/haksa/domain/user/model/User.java
  src/main/java/com/chukchuk/haksa/domain/user/service/UserService.java
Labels: 🔨 Refactor

#42 feat/Swagger 적용
  README.md
  build.gradle
  src/main/java/com/chukchuk/haksa/application/dashboard/DashboardController.java
  src/main/java/com/chukchuk/haksa/application/dashboard/dto/DashboardResponse.java
  src/main/java/com/chukchuk/haksa/domain/academic/record/controller/AcademicRecordController.java
  src/main/java/com/chukchuk/haksa/domain/academic/record/dto/AcademicRecordResponse.java
  src/main/java/com/chukchuk/haksa/domain/academic/record/dto/SemesterAcademicRecordDto.java
  src/main/java/com/chukchuk/haksa/domain/academic/record/dto/StudentAcademicRecordDto.java
  src/main/java/com/chukchuk/haksa/domain/academic/record/dto/StudentCourseDto.java
  src/main/java/com/chukchuk/haksa/domain/graduation/controller/GraduationController.java
  src/main/java/com/chukchuk/haksa/domain/graduation/dto/AreaProgressDto.java
  src/main/java/com/chukchuk/haksa/domain/graduation/dto/CourseDto.java
  src/main/java/com/chukchuk/haksa/domain/graduation/dto/GraduationProgressDto.java
  src/main/java/com/chukchuk/haksa/domain/student/controller/StudentController.java
  src/main/java/com/chukchuk/haksa/domain/student/dto/StudentSemesterDto.java
  src/main/java/com/chukchuk/haksa/domain/user/controller/UserController.java
  src/main/java/com/chukchuk/haksa/global/config/OpenApiConfig.java
  src/main/java/com/chukchuk/haksa/global/security/SecurityConfig.java
  src/main/java/com/chukchuk/haksa/global/swagger/swagger.json
  src/main/java/com/chukchuk/haksa/global/swagger/swagger.yaml
Labels: 📃 Docs, ✨ Feature

#45 fix: Id Token 검증 로직 수정
  src/main/java/com/chukchuk/haksa/global/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/chukchuk/haksa/global/security/service/KakaoOidcService.java
Labels: 🐞 BugFix

#48 feat: Custom JWT 사용, 회원가입 로직 개발
  src/main/java/com/chukchuk/haksa/domain/academic/record/controller/AcademicRecordController.java
  src/main/java/com/chukchuk/haksa/domain/academic/record/service/AcademicRecordService.java
  src/main/java/com/chukchuk/haksa/domain/academic/record/service/SemesterAcademicRecordService.java
  src/main/java/com/chukchuk/haksa/domain/auth/controller/AuthController.java
  src/main/java/com/chukchuk/haksa/domain/auth/dto/AuthDto.java
  src/main/java/com/chukchuk/haksa/domain/auth/entity/RefreshToken.java
  src/main/java/com/chukchuk/haksa/domain/auth/repository/RefreshTokenRepository.java
  src/main/java/com/chukchuk/haksa/domain/auth/service/RefreshTokenService.java
  src/main/java/com/chukchuk/haksa/domain/graduation/controller/GraduationController.java
  src/main/java/com/chukchuk/haksa/domain/graduation/service/GraduationService.java
  src/main/java/com/chukchuk/haksa/domain/student/controller/StudentController.java
  src/main/java/com/chukchuk/haksa/domain/student/service/StudentService.java
  src/main/java/com/chukchuk/haksa/domain/user/controller/UserController.java
  src/main/java/com/chukchuk/haksa/domain/user/dto/UserDto.java
  src/main/java/com/chukchuk/haksa/domain/user/service/UserService.java
  src/main/java/com/chukchuk/haksa/global/exception/InvalidTokenException.java
  src/main/java/com/chukchuk/haksa/global/security/CustomUserDetails.java
  src/main/java/com/chukchuk/haksa/global/security/SecurityConfig.java
  src/main/java/com/chukchuk/haksa/global/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/chukchuk/haksa/global/security/service/CustomUserDetailsService.java
  src/main/java/com/chukchuk/haksa/global/security/service/JwtProvider.java
  src/main/java/com/chukchuk/haksa/global/security/service/KakaoOidcService.java
Labels: 🔨 Refactor, 🐞 BugFix, ✨ Feature
